apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynode-demo
  namespace: default
  labels:
     app: mynode-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mynode-demo
  template:
    metadata:
      labels:
        app: mynode-demo
    spec:
      containers:
      - name: nodeapp
        image: 18cs024/form123
---
apiVersion: v1
kind: Service
metadata:
  name: mynode-demo
  namespace: default
  labels:
     app: mynode-demo
spec:
  type: NodePort
  selector:
    # matchLabels:
      app: mynode-demo
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30002



